version: '3'
services:
  api:
    container_name: "sample-api"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JAEGER_ENDPOINT=http://host.docker.internal:14268/api/traces
      - SERVICE_NAME=sample-api
    mem_limit: 128m
    cpus: 0.3
    restart: always

  nginx:
    image: nginx:stable-perl
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network